---
- hosts: all
  become: true
  tasks:
    - name: Gather facts about the system
      setup:

    - name: Check for Ubuntu OS
      debug:
        msg: "This is an Ubuntu-based system."
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'

    - name: Update apt cache for Ubuntu
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'

    - name: Check for CentOS OS
      debug:
        msg: "This is a CentOS-based system."
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS'

    - name: Update yum cache for CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS'
